export const notesData = [
    {
      id: 1,
      title: "Collaboration Certification Script",
      content: "This note details the step-by-step process for collaboration certification.",
      date: "12 Sep, 2024",
      isBookmarked: true,
    },
    {
      id: 2,
      title: "React Native Performance Optimization",
      content: "Techniques to improve app performance, including memory management and UI optimization.",
      date: "10 Sep, 2024",
      isBookmarked: false,
    },
    {
      id: 3,
      title: "Redux Toolkit Explained",
      content: "Understanding Redux Toolkit and how it simplifies state management in React Native apps.",
      date: "08 Sep, 2024",
      isBookmarked: true,
    },
    {
      id: 4,
      title: "AsyncStorage vs SecureStore",
      content: "Comparing storage options in React Native for handling sensitive user data securely.",
      date: "05 Sep, 2024",
      isBookmarked: false,
    },
    {
      id: 5,
      title: "React Navigation Deep Linking",
      content: "Implementing deep linking in React Native using React Navigation for better app routing.",
      date: "02 Sep, 2024",
      isBookmarked: true,
    },
    {
      id: 6,
      title: "Firebase Authentication Guide",
      content: "A complete guide to setting up Firebase authentication in a React Native app.",
      date: "30 Aug, 2024",
      isBookmarked: false,
    },
    {
      id: 7,
      title: "Styled Components in React Native",
      content: "Using styled-components for better styling and theming in React Native applications.",
      date: "28 Aug, 2024",
      isBookmarked: true,
    },
    {
      id: 8,
      title: "Building Offline-First Apps",
      content: "Techniques for building offline-first apps using Redux Persist and SQLite.",
      date: "25 Aug, 2024",
      isBookmarked: false,
    },
    {
      id: 9,
      title: "Optimizing FlatList Performance",
      content: "Best practices to optimize FlatList rendering for smooth scrolling in React Native.",
      date: "22 Aug, 2024",
      isBookmarked: true,
    },
    {
      id: 10,
      title: "GraphQL vs REST API",
      content: "A deep dive into GraphQL and REST API to decide which one suits your project best.",
      date: "20 Aug, 2024",
      isBookmarked: false,
    }
  ];

  export const TASKS = [
    {
      id: 1,
      title: "Complete React Native Project",
      description: "Finish the task card UI and integrate APIs.",
      status: "inProgress",
    },
    {
      id: 2,
      title: "Review Redux State Management",
      description: "Check how state is managed and optimize reducers.",
      status: "pending",
    },
    {
      id: 3,
      title: "Fix Navigation Issues",
      description: "Resolve stack navigation issues in the app.",
      status: "completed",
    },
    {
      id: 4,
      title: "Update UI Components",
      description: "Ensure all components are responsive and match designs.",
      status: "inProgress",
    },
    {
      id: 5,
      title: "Write Unit Tests",
      description: "Cover major functions with Jest and React Native Testing Library.",
      status: "pending",
    },
  ]
  
  export const todoData = [
    {
      title: "Go for groceries",
      items: [
        "Cauliflower",
        "Potato",
        "Ladyfinger",
        "Tomatoes",
        "Spinach",
        "Milk",
        "Eggs",
        "Bread",
        "Cheese",
      ],
      status: "In process",
    },
    {
      title: "Workout",
      items: ["Push-ups", "Squats", "Running", "Deadlifts", "Pull-ups", "Plank", "Yoga"],
      status: "Pending",
    },
    {
      title: "Read a book",
      items: [
        "Atomic Habits",
        "Deep Work",
        "The Alchemist",
        "The Subtle Art of Not Giving a F*ck",
        "Rich Dad Poor Dad",
        "1984",
        "Sapiens",
        "The Psychology of Money",
      ],
      status: "Completed",
    },
    {
      title: "Complete React Task",
      items: [
        "Build UI",
        "Fix bugs",
        "Optimize performance",
        "Refactor components",
        "Improve accessibility",
        "Update dependencies",
        "Write unit tests",
        "Deploy to production",
      ],
      status: "In process",
    },
    {
      title: "Prepare Lunch",
      items: ["Rice", "Dal", "Salad", "Paneer Tikka", "Chicken Curry", "Roti", "Curd", "Lassi"],
      status: "Pending",
    },
    {
      title: "Meeting with Team",
      items: [
        "Discuss project",
        "Review code",
        "Set deadlines",
        "Brainstorm ideas",
        "Allocate tasks",
        "Check team progress",
        "Plan next sprint",
      ],
      status: "Completed",
    },
    {
      title: "Evening Walk",
      items: [
        "Walk 5km",
        "Stretching",
        "Hydrate",
        "Meditate in the park",
        "Take a pet along",
        "Listen to a podcast",
      ],
      status: "In process",
    },
    {
      title: "Weekend Trip Planning",
      items: [
        "Book tickets",
        "Hotel reservation",
        "Pack essentials",
        "Create itinerary",
        "Check weather forecast",
        "Reserve restaurants",
        "Download offline maps",
        "Arrange transport",
      ],
      status: "Pending",
    },
    {
      title: "Pay Bills",
      items: [
        "Electricity",
        "Internet",
        "Credit card",
        "Water bill",
        "Gas bill",
        "Phone recharge",
        "Loan EMI",
        "Insurance premium",
      ],
      status: "Completed",
    },
    {
      title: "Family Time",
      items: [
        "Movie night",
        "Board games",
        "Dinner together",
        "Family storytelling",
        "Outdoor picnic",
        "Photo album review",
        "Gardening together",
        "Music session",
      ],
      status: "Pending",
    },
  ];
  
  
  